services:
  - type: web
    name: safari-bus-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: your-render-db-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://safaribus.onrender.com
